### ISSUE TITLE
Unable to open mp4 files

### ISSUE THREAD

**Issue by catazep** [stfkolev/Decoder#4]
Hi man,

Thanks for you work, very nice of you :)
Little mention: I had to add "System.Data.SQLite.Core" into UI in order to make it work. (Probably an sql bug)

Anyway I was able to convert the files, but I can't find a media player that is able to run them. For example the basic windows media player tells me that the file might be corrupted or I don't have the required codec.
I'd like to find a solution by myself, but I don't really understand the process of decoding.

If you have any suggestions that'd be great:)

Have a great day!

**Comment by devguru-udus** [comment]
same here, i cant play any mp4 video, i think pluralsight have blocked it

**Comment by dahikino** [comment]
the mp4 generated with the key are not anymore in the mp4 specification standard. the content of the mp4 is now unreadable.

**Comment by dahikino** [comment]
I found finally the code for encrypt/decrypt/XorgBuffer that concerned the last version of the offline player of PS

**Comment by miguelxp2010** [comment]
Dahikino, could you please update VideoEncryption.XorBuffer(), str1, str2 located in VideoEncryption.cs file or share the new code?

**Comment by stfkolev** [comment]
Will take a look at it! Sorry for the late response!

**Comment by catazep** [comment]
It works🤩
Thank you!

**Comment by deep-intellify** [comment]
Hey, I'm having the same problem with the latest release. The mp4 files are unreadable. Can you help me out?
